[start]
command:/usr/local/etc/rc.d/adguardhome start && sleep 1
parameters:
type:script
message:Starting AdGuard Home service

[stop]
command:/usr/local/etc/rc.d/adguardhome stop
parameters:
type:script
message:Stopping AdGuard Home service

[restart]
command:/usr/local/etc/rc.d/adguardhome restart && sleep 1
parameters:
type:script
message:Restarting AdGuard Home service
description:Restart AdGuard Home service

[status]
command:/usr/local/etc/rc.d/adguardhome status; exit 0
parameters:
type:script_output
message:Request AdGuard Home status

[dashboard]
command:/usr/local/opnsense/scripts/adguardhome/dashboard.py
parameters:%s
type:script_output
message:Fetching AdGuard Home dashboard data

[querylog]
command:/usr/local/opnsense/scripts/adguardhome/querylog.py
parameters:%s
type:script_output
message:Fetching AdGuard Home query log data
