###################################################################
# Local syslog-ng configuration filter definition [adguardhome].
###################################################################
filter f_local_adguardhome {
    program("adguardhome");
};
