PLUGIN_NAME=		theme-dracula
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		The dracula theme - dark purple/pink
PLUGIN_MAINTAINER=	joe.roback@gmail.com
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
