PLUGIN_NAME=        adguardhome
PLUGIN_VERSION=     1.0.0
PLUGIN_COMMENT=     AdGuard Home plugin for OPNsense
PLUGIN_WWW=         https://github.com/AdguardTeam/AdGuardHome
PLUGIN_MAINTAINER=  joe.roback@gmail.com

.include "../../Mk/plugins.mk"
